# This is your proxy secret
# This prevents other proxies players from connecting to your server
# Any player that connects with an unmatched secret will be kicked
proxy:
  # You can disable secret verification by leaving it empty,
  # WARNING: That puts your server at-risk, since auth is disabled, any player can join as any name they like
  secret: "xZeroMCPE"

messages:
  disconnect-proxy: "Ouch man! something is wrong with your connection"